<a href="https://colab.research.google.com/github/kurihara-ryo/cesarean-pasaran/blob/main/%E3%80%90%E8%A7%A3%E7%AD%94%E4%BE%8B%E3%80%91%E7%99%BA%E5%B1%95%E8%AA%B2%E9%A1%8C_%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E2%85%A2_0102_ipynb_%E3%81%AE%E3%82%B3%E3%83%94%E3%83%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 各課題について、コメントを参考にしてプログラムを書いてください。
# 実行ボタンを押して、プログラムが正しく実行されることを確認してください。
# 提出の際は、コメントを削除せずに残してください。
# 全ての課題を解けなかった場合でも、〆切までに提出すれば途中点が付与されます。

課題1

タンパク質のアミノ酸配列`s`を引数として、one-hot encodingを戻り値とする関数`onehot_encoding_aa()`を書いてください。one-hot encodingはshapeが`(len(s), 20)`の2次元アレイとし、どのアミノ酸が何列目に対応するかは辞書`AA2Index`を参照してください。

この関数を使って、下記の配列`seq`のone-hot encodingを表示してください。



In [ ]:
import numpy as np

AA2Index = {
    'A':  0, 'R':  1, 'N':  2,  'D': 3, 'C':  4, 'Q':  5, 'E':  6, 'G':  7, 'H':  8, 'I':  9,
    'L': 10, 'K': 11, 'M': 12, 'F': 13, 'P': 14, 'S': 15, 'T': 16, 'W': 17, 'Y': 18, 'V': 19
}

seq = 'MGLSDGEWQLVLNVW'

def onehot_encoding_aa(s):
    # まず、0のみからなるlen(s)行20列の行列を作る。
    res = np.zeros((len(s), 20))
    # 次に、sを1文字ずつ見ながら、行列の該当する場所に1を代入していく。
    for i in range(len(s)):
        res[i, AA2Index[s[i]]] = 1
    return res

# 簡単な例で動作確認
print('one-hot encoding for AN:')
print(onehot_encoding_aa('AN'), '\n')

# seqのone-hot encodingを表示
print('one-hot encoding for {}:'.format(seq))
print(onehot_encoding_aa(seq))

one-hot encoding for AN:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 

one-hot encoding for MGLSDGEWQLVLNVW:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

課題2

カーネル行列とは、データの全てのペアに対してカーネル関数を計算して、それらの値を行列に格納したものです。`n`個のデータがあるとき、カーネル行列`K`の`i`行`j`列の要素は、`i`番目のデータと`j`番目のデータのカーネル関数の値になります。

$$
K_{i,j} = k(\mathbf{x}_{i}, \mathbf{x}_{j})
$$

下記の2次元アレイ`X`は、5個の3次元データを表しています。この`X`と演習課題で書いた関数`rbf_kernel()`を使って、カーネル行列を計算して表示してください。

In [ ]:
import numpy as np

# RBFカーネル
def rbf_kernel(x, y):
    # 演習課題で書いたものをコピペする
    return np.exp(-0.1 * np.sum((x - y) ** 2))

# 5個の3次元データ
X = np.array([0.50, -0.14,  0.65,
              1.52, -0.23, -0.23,
              1.58,  0.77, -0.47,
              0.54, -0.46, -0.47,
              0.24, -1.91, -1.72])
X = X.reshape(5, 3)

# カーネル行列を計算
K = np.zeros((X.shape[0], X.shape[0]))
for i in range(X.shape[0]):
    # 対称行列なので上三角部分だけ計算してコピーしてもいい
    for j in range(i, X.shape[0]):
        K[i][j] = rbf_kernel(X[i, :], X[j, :])
        if i != j:
            K[j][i] = K[i][j]

# カーネル行列を表示
print('Kernel matrix K:')
print(K)

Kernel matrix K:
[[1.         0.83335963 0.72260684 0.8729823  0.41406182]
 [0.83335963 1.         0.89931672 0.89844481 0.51268688]
 [0.72260684 0.89931672 1.         0.77147578 0.34852337]
 [0.8729823  0.89844481 0.77147578 1.         0.68694572]
 [0.41406182 0.51268688 0.34852337 0.68694572 1.        ]]


課題3

辞書`Codon2AA`は、コドンとアミノ酸の対応関係（遺伝暗号）を表しています。遺伝暗号表において、同じアミノ酸をコードしているコドンを同義コドンと呼びます。例えば、TTTとTTCはどちらもアミノ酸Fをコードしているため同義コドンの関係にあります。

下記の配列seqに対して、同じアミノ酸配列をコードする塩基配列が何通り存在するか計算してください。



In [ ]:
Codon2AA = {
    "TTT":"F","TTC":"F","TTA":"L","TTG":"L","CTT":"L","CTC":"L","CTA":"L","CTG":"L",
    "ATT":"I","ATC":"I","ATA":"I","ATG":"M","GTT":"V","GTC":"V","GTA":"V","GTG":"V",
    "TCT":"S","TCC":"S","TCA":"S","TCG":"S","AGT":"S","AGC":"S","CCT":"P","CCC":"P",
    "CCA":"P","CCG":"P","ACT":"T","ACC":"T","ACA":"T","ACG":"T","GCT":"A","GCC":"A",
    "GCA":"A","GCG":"A","TAT":"Y","TAC":"Y","CAT":"H","CAC":"H","CAA":"Q","CAG":"Q",
    "AAT":"N","AAC":"N","AAA":"K","AAG":"K","GAT":"D","GAC":"D","GAA":"E","GAG":"E",
    "TGT":"C","TGC":"C","TGG":"W","CGT":"R","CGC":"R","CGA":"R","CGG":"R","AGA":"R",
    "AGG":"R","GGT":"G","GGC":"G","GGA":"G","GGG":"G","TAA":"*","TAG":"*","TGA":"*"
}

seq = 'MGLSDGEWQLVLNVW'

# 考え方
# 例として、2文字のアミノ酸配列ANを考える。
# 遺伝暗号表を見ると、Aには同義コドンが4種類、Nには同義コドンが2種類存在する。
# そのため、ANをコードする塩基配列は4 * 2 = 8種類存在する。
#
# つまり、配列の各文字について、同義コドンの数を掛けあわせていけばいい。
# アミノ酸をキー、同義コドンの数を値とする辞書があると便利そうだ。

# アミノ酸をキー、同義コドンの数を値とする辞書
aa2n = {}
for k,v in Codon2AA.items():
    if v not in aa2n:
        aa2n[v] = 1
    else:
        aa2n[v] += 1

# seqをコードする塩基配列の数を計算
n_synonymous = 1
for i in range(len(seq)):
    n_synonymous *= aa2n[seq[i]]

print(n_synonymous)

5308416


課題4

work_record.csvをデータフレームとして読み込み、Aさん、Bさん、Cさんそれぞれについて、1年間の給料の合計金額を計算してください。給料は時給制であり、以下のルールで決まるものとします。

*  平日は時給2,500円。ただし、1日8時間以上勤務した場合、8時間を超えた分については時給3,000円。
*  土曜日曜は時給2,800円。ただし、1日8時間以上勤務した場合、8時間を超えた分については時給3,500円。

例えば、平日に10時間勤務すると、その日の給料は`2,500*8 + 3000*2 = 26,000`円になります。

In [ ]:
import gdown
import pandas as pd
import numpy as np

# ここは演習課題と同じ
url='https://drive.google.com/uc?export=download&id=1an_a2CVQzX9gyeQ2_IxoU2EYjieC-mIC'
gdown.download(url, 'work_record.csv', quiet=False)
df = pd.read_csv('work_record.csv')
display(df)
print('\n')

# 考え方の例
# 1) まず土曜日曜について給料の合計金額を計算する
# 1-1) query()を使って土曜日曜のデータを抽出
# 1-2) iloc[]を使って勤務時間の部分を切り出す
# 1-3) apply()を使って、3人それぞれについて給料の和を計算
# apply()に入れる関数は自分で書く必要がある
# 労働時間の入ったリストを引数として、給料の和を計算する関数が必要

# 2) 1と同様に平日の給料の合計金額を計算する

# 3) 1と2の結果を合計する

# 勤務時間のリストから給料の和を計算する関数、土曜日曜バージョン
def salary_sum_weekend(hours):
    s = 0
    for h in hours:
        if h < 8:
            s += 2800 * h
        else:
            s += 2800 * 8 + 3500 * (h - 8)
    return s

# 勤務時間のリストから給料の和を計算する関数、平日バージョン
def salary_sum_weekday(hours):
    s = 0
    for h in hours:
        if h < 8:
            s += 2500 * h
        else:
            s += 2500 * 8 + 3000 * (h - 8)
    return s

print('土曜日曜の給料の合計金額')
df_weekend = df.query("曜日 == '土' or 曜日 == '日'")
weekend = df_weekend.iloc[:, 4:].apply(salary_sum_weekend, axis=0)
weekend.index = ['Aさん', 'Bさん', 'Cさん']
display(weekend)
print('\n')

print('平日の給料の合計金額')
df_weekday = df.query("曜日 != '土' and 曜日 != '日'")
weekday = df_weekday.iloc[:, 4:].apply(salary_sum_weekday, axis=0)
weekday.index = ['Aさん', 'Bさん', 'Cさん']
display(weekday)
print('\n')

print('給料の合計金額')
display(weekday + weekend)

Downloading...
From: https://drive.google.com/uc?export=download&id=1an_a2CVQzX9gyeQ2_IxoU2EYjieC-mIC
To: /content/work_record.csv
100%|██████████| 10.0k/10.0k [00:00<00:00, 11.6MB/s]


年   月   日 曜日  Aさん_勤務時間  Bさん_勤務時間  Cさん_勤務時間
0    2025   1   1  水      8.03      8.92      8.58
1    2025   1   2  木      8.38      7.69      7.69
2    2025   1   3  金      7.54      8.79      8.38
3    2025   1   4  土      0.00      8.95      0.00
4    2025   1   5  日      0.00      0.00      0.00
..    ...  ..  .. ..       ...       ...       ...
360  2025  12  27  土      0.00      0.00      0.00
361  2025  12  28  日      0.00      0.00      0.00
362  2025  12  29  月      8.95      8.82      8.89
363  2025  12  30  火      8.99      7.72      8.06
364  2025  12  31  水      8.63      8.53      7.69

[365 rows x 7 columns]



土曜日曜の給料の合計金額


Aさん     96523.0
Bさん    183841.0
Cさん     68628.0
dtype: float64



平日の給料の合計金額


Aさん    5408845.0
Bさん    5402555.0
Cさん    5373590.0
dtype: float64



給料の合計金額


Aさん    5505368.0
Bさん    5586396.0
Cさん    5442218.0
dtype: float64