<a href="https://colab.research.google.com/github/kurihara-ryo/cesarean-pasaran/blob/main/%E3%80%90%E8%A7%A3%E7%AD%94%E4%BE%8B%E3%80%91%E7%99%BA%E5%B1%95%E8%AA%B2%E9%A1%8C_%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E2%85%A2_0304.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 各課題について、コメントを参考にしてプログラムを書いてください。
# 実行ボタンを押して、プログラムが正しく実行されることを確認してください。
# 提出の際は、コメントを削除せずに残してください。
# 全ての課題を解けなかった場合でも、〆切までに提出すれば途中点が付与されます。

課題1

accuracyなどの精度指標がクラス確率の閾値に依存することを確認してみましょう。

10個のデータに対する2クラス分類問題を考えます。以下の`y_test`は真のクラスを表しており、`y_test_prob`は分類モデルによって予測されたクラス確率を表しています。`y_test_prob`の0列目がクラス0の確率、1列目がクラス1の確率です。通常、クラス確率の閾値には0.5を使うので、クラス1の確率が0.5より大きいデータをクラス1、それ以外のデータをクラス0に分類します。この結果が`y_test_pred`に入っています。

閾値を0.7にした場合のクラス分類の結果`y_test_pred_07`と、これに対するaccuracyを計算して表示してください。また、閾値を0.2にした場合のクラス分類の結果`y_test_pred_02`とaccuracyを計算して表示してください。

In [1]:
import numpy as np
from sklearn.metrics import accuracy_score

# 真のクラス
y_test = np.array([0, 1, 1, 0, 0, 0, 0, 1, 0, 0])

# クラス確率
y_test_prob = np.array([0.62545988, 0.37454012,
                        0.04928569, 0.95071431,
                        0.26800606, 0.73199394,
                        0.40134152, 0.59865848,
                        0.84398136, 0.15601864,
                        0.84400548, 0.15599452,
                        0.94191639, 0.05808361,
                        0.13382385, 0.86617615,
                        0.39888499, 0.60111501,
                        0.29192742, 0.70807258])
y_test_prob = y_test_prob.reshape(10, 2)

# クラス確率の閾値を0.5にした場合の予測クラス
y_test_pred = np.zeros(y_test_prob.shape[0])
for i in range(y_test_prob.shape[0]):
    if y_test_prob[i, 1] > 0.5:
        y_test_pred[i] = 1
    else:
        y_test_pred[i] = 0
print('y_test_pred with threshold=0.5\n{}'.format(y_test_pred))
# 閾値0.5でのaccuracy
print('accuracy with threshold=0.5\n{}'.format(accuracy_score(y_true=y_test, y_pred=y_test_pred)))

# クラス確率の閾値を0.7にした場合の予測クラス
y_test_pred_07 = np.zeros(y_test_prob.shape[0])
for i in range(y_test_prob.shape[0]):
    if y_test_prob[i, 1] > 0.7:
        y_test_pred_07[i] = 1
    else:
        y_test_pred_07[i] = 0
print('y_test_pred with threshold=0.7\n{}'.format(y_test_pred_07))
# 閾値0.7でのaccuracy
print('accuracy with threshold=0.7\n{}'.format(accuracy_score(y_true=y_test, y_pred=y_test_pred_07)))

# クラス確率の閾値を0.2にした場合の予測クラス
y_test_pred_02 = np.zeros(y_test_prob.shape[0])
for i in range(y_test_prob.shape[0]):
    if y_test_prob[i, 1] > 0.2:
        y_test_pred_02[i] = 1
    else:
        y_test_pred_02[i] = 0
print('y_test_pred with threshold=0.2\n{}'.format(y_test_pred_02))
# 閾値0.2でのaccuracy
print('accuracy with threshold=0.2\n{}'.format(accuracy_score(y_true=y_test, y_pred=y_test_pred_02)))

y_test_pred with threshold=0.5
[0. 1. 1. 1. 0. 0. 0. 1. 1. 1.]
accuracy with threshold=0.5
0.7
y_test_pred with threshold=0.7
[0. 1. 1. 0. 0. 0. 0. 1. 0. 1.]
accuracy with threshold=0.7
0.9
y_test_pred with threshold=0.2
[1. 1. 1. 1. 0. 0. 0. 1. 1. 1.]
accuracy with threshold=0.2
0.6


課題2

演習課題では、モデルの性能評価を目的として、データを学習データとテストデータに分割して、学習データに対してハイパラの調整とモデルの学習を行い、テストデータに対する予測精度を評価しました。一方、機械学習を実問題に適用する際には、データ全体を用いてハイパラ調整とモデル学習を行い、ラベルの付いていない（正解の分からない）新しいデータに対して予測を行う必要があります。このような解析を体験してみましょう。

heart_failure_clinical_records.csvを用いて、演習課題のような性能評価を様々なモデルについて行った結果、このデータにおいてはランダムフォレストが最も良いモデルであると結論を出したと仮定します。その後、病院から新しい患者10名の臨床情報heart_failure_clinical_records_new.csvを受け取りました。これらの患者は存命中であるため、csvファイル内にDEATH_EVENTの列は存在しません。治療の方針や優先度を決めるために、機械学習で各患者の死亡確率を予測したいとします。

以下の手順に沿って、各患者の死亡確率を計算し、死亡確率の最も高い患者を同定してください。

1.   heart_failure_clinical_records.csvの全てのデータを使って、ランダムフォレストのハイパラ調整とモデル学習を行ってください。乱数シード、ハイパラの探索範囲、CVの分割数については、コード内の指示にしたがってください。精度指標はROC AUCとします。
2.   1.で作成したモデルを使って、heart_failure_clinical_records_new.csvの各患者に対してクラス確率を計算して表示してください。
3.   死亡確率（クラス1の確率）が最も高いのはデータフレーム内の何番目の患者か、コメントの解答欄に書いてください。一番上の患者を0番目とします。


In [ ]:
import numpy as np
import pandas as pd
import gdown

# 演習課題と同じデータ
url='https://drive.google.com/uc?export=download&id=170BvFfMQJBI8jueqdMXuJiB910bbKSiN'
gdown.download(url, 'heart_failure_clinical_records.csv', quiet=False)
df = pd.read_csv('heart_failure_clinical_records.csv')

# 新しい患者のデータ。DEATH_EVENTの列は存在しない。
url='https://drive.google.com/uc?export=download&id=1foR7RCoqlVva_rRuwBvpIo7OVzA2uVQ5'
gdown.download(url, 'heart_failure_clinical_records_new.csv', quiet=False)
df_new = pd.read_csv('heart_failure_clinical_records_new.csv')
display(df_new)

# 必要なモジュール一式を用意
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import GridSearchCV

# 乱数シードには以下の値を用いてください
seed = 4649

# ハイパラの探索範囲は以下のようにしてください
param_grid = {'n_estimators': [10, 20, 50, 100]}


#### ここからコードを書いてください

# 1) heart_failure_clinical_records.csvの全てのデータを使って、
# ハイパラ調整とモデルの学習を行う。

# 1-1) データフレームをX,yに分ける
X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]
print('X shape {}'.format(X.shape))
print('y shape {}'.format(y.shape))

# 1-2) Xの前処理
scaler = StandardScaler()
X = scaler.fit_transform(X)
# ここで作ったscalerは新しい患者データの前処理にも使用

# 1-3) モデルのインスタンスを作成
model = RandomForestClassifier(random_state=seed)

# 1-4) CVの方法を指定
# 分割数は5としてください
cv = KFold(n_splits=5, shuffle=True, random_state=seed)

# 1-5) グリッドサーチの方法を指定
# 精度指標にはROC AUCを使用してください
gs = GridSearchCV(estimator=model, param_grid=param_grid, cv=cv, scoring='roc_auc')

# 1-6) ROC AUCの最も良いハイパラを選択
gs.fit(X=X, y=y)
print('best hyperparameter: {}'.format(gs.best_params_))
print('best ROC AUC: {}\n'.format(gs.best_score_))


# 2) 1)で作成したモデルを使って、
# heart_failure_clinical_records_new.csvの各患者に対してクラス確率を計算

# 2-1) DEATH_EVENTは存在しないため、X,yに分ける必要はない
# データフレーム全体をX_newとする
X_new = df_new

# 2-2) データの前処理
# Xと同じ基準で変換するために、Xに使用したのと同じインスタンスを流用
X_new = scaler.transform(X_new)

# 2-3) クラス確率の計算
y_new_prob = gs.predict_proba(X_new)
print('Class probability for new patients:\n{}'.format(y_new_prob))


# 3) 死亡確率の最も高い患者を同定
print('Patient with highest death probability:\n{}'.format(y_new_prob[:, 1].argmax()))

# 解答欄：死亡確率の最も高い患者は？
# 3番目の患者

Downloading...
From: https://drive.google.com/uc?export=download&id=170BvFfMQJBI8jueqdMXuJiB910bbKSiN
To: /content/heart_failure_clinical_records.csv
100%|██████████| 11.5k/11.5k [00:00<00:00, 11.0MB/s]
Downloading...
From: https://drive.google.com/uc?export=download&id=1foR7RCoqlVva_rRuwBvpIo7OVzA2uVQ5
To: /content/heart_failure_clinical_records_new.csv
100%|██████████| 576/576 [00:00<00:00, 960kB/s]


age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0   63        1                    6174.0         0               35.3   
1   69        1                    6924.7         0               20.5   
2   82        0                    2409.5         0               70.5   
3   88        0                    5540.9         0               46.2   
4   58        1                    7269.5         0               26.6   
5   79        0                    3411.9         0               50.2   
6   77        1                    2246.0         0               25.7   
7   56        1                    2123.1         0               75.2   
8   48        1                    1610.4         0               28.6   
9   85        1                    2140.4         1               30.3   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    0   754708.0               2.4         117.8    1   
1                    0   437022.6               6.4         119.9    1   
2                    0   484814.8               6.5         131.2    0   
3                    1   223705.9               9.2         130.4    0   
4                    1   304732.3               0.5         126.9    1   
5                    1   761850.0               0.6         114.5    1   
6                    0   129316.0               8.5         124.8    1   
7                    0   784643.1               6.4         121.7    1   
8                    0   147871.4               2.2         127.3    0   
9                    1   462308.2               2.8         141.5    0   

   smoking  
0        0  
1        1  
2        0  
3        0  
4        0  
5        0  
6        0  
7        1  
8        0  
9        1

X shape (299, 11)
y shape (299,)
best hyperparameter: {'n_estimators': 100}
best ROC AUC: 0.7796668478878844

Class probability for new patients:
[[0.51 0.49]
 [0.29 0.71]
 [0.42 0.58]
 [0.27 0.73]
 [0.4  0.6 ]
 [0.54 0.46]
 [0.37 0.63]
 [0.48 0.52]
 [0.45 0.55]
 [0.34 0.66]]
Patient with highest death probability:
3


課題3

プロモータとは、遺伝子の上流部分にあり、その遺伝子の転写を活性化する機能をもった領域のことを指します。プロモータのDNA配列の違いによって、遺伝子の転写活性が変化することが知られています。近年では、機械学習を用いてプロモータのDNA配列から転写活性を予測することで、人工的な高活性プロモータをデザインする研究が行われています。

promoter_activity.csvには、様々な人工プロモータのDNA配列とその転写活性が記載されています。このデータを用いて、DNA配列から転写活性を予測するランダムフォレストの回帰モデルを作成し、予測精度を評価してください。

*   入力Xには、データフレーム内のpromoter_sequenceからone-hot encodingを計算して使用してください。
*   予測対象yには、データフレーム内のtranscription_activityを用いてください。
*   乱数シード、学習データとテストデータの分割比率、ハイパラの探索範囲、CVの分割数については、コード内の指示にしたがってください。精度指標はR2とします。

データの出典：[LaFleur et al. Nat Commun. 2022.](https://doi.org/10.1038/s41467-022-32829-5) より一部抜粋。

In [ ]:
# データの確認
# このセルは実行するだけ
import gdown
import pandas as pd
import numpy as np

url='https://drive.google.com/uc?export=download&id=1OjDryc69PuhvsjK5B2wtmxwHSchU-dXN'
gdown.download(url, 'promoter_activity.csv', quiet=False)
df = pd.read_csv('promoter_activity.csv')
display(df)

Downloading...
From: https://drive.google.com/uc?export=download&id=1OjDryc69PuhvsjK5B2wtmxwHSchU-dXN
To: /content/promoter_activity.csv
100%|██████████| 86.9k/86.9k [00:00<00:00, 6.11MB/s]


promoter_sequence  transcription_activity
0    TTTTCTATCTACGTACTTGACACTATTTCCTATTTCTCTTACCGCT...               -2.297722
1    TTTTCTATCTACGTACTTGACACTATTTCCTATTTCTCTCTCCTGT...               -1.788633
2    TTTTCTATCTACGTACTTGACACTATTTCCTATTTCTCTGGGCTTT...               -2.241245
3    TTTTCTATCTACGTACTTGACACTATTTCCTATTTCTCTGGAGCCT...               -1.950505
4    TTTTCTATCTACGTACTTGACACTATTTCCTATTTCTCTACACTCT...               -3.435533
..                                                 ...                     ...
995  TTTTCTATCTACGTACTTGACACTATTTCCTATTTCTCTTTATGCT...               -3.379485
996  TTTTCTATCTACGTACTTGACACTATTTCCTATTTCTCTTATAATG...               -4.022645
997  TTTTCTATCTACGTACTTGACACTATTTCCTATTTCTCTTACTTAT...               -2.723506
998  TTTTCTATCTACGTACATTGGTCTATTTCCTATTTCTCTTATAATT...               -2.070849
999  TTTTCTATCTACGTACTTGACACTATTTCCTATTTCTCTGTTCCAT...               -1.905887

[1000 rows x 2 columns]

In [ ]:
# ここから課題

# 1) Xの作成
# df内のpromoter_sequenceからone-hot encodingを計算

# ヒント1：
# df内の配列はどれも長さ73なので、one-hot encodingのshapeは(73, 4)になる。
# これを特徴ベクトルとして使用するために、
# flatten()などのメソッドを使って1次元アレイに変換する。
# 特徴ベクトルの長さは73 x 4 = 292になる。
Base2Index = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
def onehot_encoding(s):
    res = np.zeros((len(s), 4))
    for i in range(len(s)):
        res[i, Base2Index[s[i]]] = 1
    return res.flatten() # 1次元アレイに変換

# ヒント2：
# Xはshapeが(データ数, 292)の行列になる。
# one-hot encodingは標準化せずに用いるのが一般的なので、
# StandardScaler()は使用せずにそのまま用いてよい。
X = np.zeros([df.shape[0], 292])
for i in range(df.shape[0]):
    X[i, :] = onehot_encoding(df['promoter_sequence'][i])
print(X.shape)

# 2) yの作成
# df内のtranscription_activityをそのまま使用
y = df['transcription_activity']


# 3) モデルの作成と評価

# 必要なモジュール一式を用意
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import GridSearchCV

# 乱数シードには以下の値を用いてください
seed = 1234

# X,yをそれぞれ学習データとテストデータに分ける
# 分割比率は、train:test = 7:3としてください
X_train,  X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=True, random_state=seed)
print('X_train shape {}'.format(X_train.shape))
print('X_test shape {}'.format(X_test.shape))
print('y_train shape {}'.format(y_train.shape))
print('y_test shape {}'.format(y_test.shape))

# モデルのインスタンスを作成
model = RandomForestRegressor(random_state=seed)
# ハイパラの探索範囲は以下のようにしてください
param_grid = {'n_estimators': [10, 20, 50, 100]}

# CVの方法を指定
# 分割数は5としてください
cv = KFold(n_splits=5, shuffle=True, random_state=seed)

# グリッドサーチの方法を指定
# 精度指標にはR2を使用してください
gs = GridSearchCV(estimator=model, param_grid=param_grid, cv=cv, scoring='r2')

# グリッドサーチを実行
# R2の最も良いハイパラを選択
gs.fit(X=X_train, y=y_train)
print('best hyperparameter: {}'.format(gs.best_params_))
print('best R2: {}'.format(gs.best_score_))

# テストデータに対する予測精度を評価
y_test_pred = gs.predict(X_test) # 予測値

r2_test = r2_score(y_true=y_test, y_pred=y_test_pred)
print('R2 on test data: {}'.format(r2_test))

(1000, 292)
X_train shape (700, 292)
X_test shape (300, 292)
y_train shape (700,)
y_test shape (300,)
best hyperparameter: {'n_estimators': 100}
best R2: 0.5159404796306453
R2 on test data: 0.5095514812485415
